MESSAGES=186
LOCALE=1 Deutsch
~Datei
~Optionen
~Hilfe
~Neue Verbindung
S~chlieáe Verbindung
~Verbinde
~Trenne
Server ~sichern
Server ~l”schen
Be~enden
~Voreinstellungen
Server ~verwalten
~Automatisch verbinden
Autom. ~neu verbinden
~Standardsortierung
nach Name
nach Datum
nach Gr”áe
keine
~Index
~Hilfe
~Systeminformation
Handy~FTP im Web
š~ber
Sort.
Verzeichnis anlegen
Umbenennen
L”schen
Datei betrachten
Warteschlange speichern
Warteschlange laden
Datei entfernen
Absturz in %s, Zeile %d von %s. Bitte melden Sie dies an dbsoft@technologist.com
Seite %d von %
Einstellungen konnten nicht gespeichert werden. Inipath = \"%s\"
Gespeicherter Server \"%s\" ist nicht identisch!
Servertyp nicht gefunden! Benutze Standardeinstellungen.
Entferntes Verzeichnis empfangen.
Mit entferntem Verzeichnis verbunden.
Sende lokales LIST Kommando.
Fehler beim Empfangen des lokalen Verzeichnisses!
Von lokalem Verzeichnis getrennt.
Laufwerk %c:
Lokales Verzeichnis empfangen.
Mit lokalem Verzeichnis verbunden.
Gr”áe
Zeit
Datum
Fehler beim Anlegen des Containers!
Ziel
Verzeichnis
Gr”áe
Zeit
Datum
šber HandyFTP
Voreinstellungen
Allgemein
™ffne alle Server
Passiv-FTP
Zeige Passwort
URLs sichern
Spalten optimieren
Timeout
Wiederholversuche
Cache-Begrenzung
Bandbreiten-Begrenzung
Lokale
Ok
Abbrechen
IPS server ist nicht unt„tig.
IPS server ist nicht unt„tig.
IPS server ist nicht unt„tig.
Benutzer
Adresse
Aktivit„t
unt„tig
Socket
Konnte IPS Server nicht validieren.
IPS Administration
Schlieáen
Benutzer trennen
Herunterfahren
Neustarten
Administration
Servertyp
InetPowerServer
Andere
Erzeuge Verzeichnis \"%s\"
Benenne \"%s\" um in \"%s\"
Systeminformation
HandyFTP:\r\n\r\nErzeugt am: %s\r\nErzeugt um: %s\r\n\r\n
System:\r\n\r\nFarbtiefe: %lu\r\n
Bildschirmbreite: %d\r\nBildschirmh”he: %d\r\n\r\n
Dynamic Windows:\r\n\r\nVersion: %d.%d.%d\r\nErzeugt am: %s\r\nErzeugt um: %s\r\n\r\nBetriebssystem:\r\n\r\nSystem: %s\r\nVersion: %d.%d
\r\nStand: %d
Sendevorgang begonnen...
Empfang begonnen...
%d bytes %s in %d:%.2d (%.2fK/s ETA %d:%.2d).
versandt
empfangen
Von entferntem Verzeichnis getrennt.
šbertragung abgeschlossen. %d bytes empfangen in %d Sekunden (%.2fK/s).
Timeout berschritten beim Warten auf Unt„tigkeit des Servers.
Versuche Verbindung herzustellen... Bitte warten.
Kann Servername nicht aufl”sen.
Konnte keine Verbindung herstellen.
Verbunden mit %s auf Port %d.
Verbunden.
Sende QUIT-Nachricht an entfernten Server...
Verbindung mit %s auf Port %d geschlossen.
Warte auf Unt„tigkeit des Ziels. (%ds)
Zielserver nicht gefunden!
Konnte lokale Datei \"%s\" nicht finden.
Fehler beim Anbinden an Port der Datenverbindung.
M”glicherweise falsche Seitenkennung empfangen.
Konnte lokale Datei \"%s\" nicht finden.
Dieser Server ist ausgelastet.
Wechsle Arbeitsverzeichnis zu \"%s\".
Fataler FXP-Fehler! (THRDFXP) Abbruch.
Benutze Servertyp \"%s\" (%d)
Konnte Servertypen nicht laden, trenne.
Server gibt \"%s\" als Arbeitsverzeichnis an.
%s meldet Dateiname als nicht verfgbar.
%s meldet lokalen Fehler bei der Bearbeitung.
%s meldet unzureichenden Speicherplatz.
%s meldet Datei als nicht verfgbar.
%s meldet Seitentyp als unbekannt.
%s meldet šberschrietung der Speicherplatzbelegung.
%s meldet Dateiname als unzul„ssig.
Wechsle in den passiven Modus.
FXP-šbertragung erfolgreich abgeschlossen.
Wechsle Arbeitsverzeichnis zu \"%s\".
Fehler beim Anbinden an den Port der Datenverbindung.
Abbruch durch anderen Server, erneuter Versuch.
Fehler beim Herstellen der Verbindung.
Datenverbindung hergestellt.
Fataler FXP-Fehler! (STATUSFXPRETR) Abbruch.
Fataler FXP-Fehler! (STATUSFXPSTOR) Abbruch.
šbertragung abgeschlossen. %d bytes gesendet in %d Sekunden (%.2fK/s).
šbertragung abgeschlossen.
Maximale Anzahl der Versuche erreicht, fahre mit n„chstem Eintrag fort.
Letzter Reiter kann nicht entfernt werden.
Fehler beim Erzeugen der Datenpipes! Reitererzeugung abgebrochen.
Konnte neuen Reiter nicht erzeugen!
Seite 1 von 1
Servertitel:
Servername:
Port:
Benutzername:
Passwort:
Verzeichnis:
Ziel:
Willkommen bei HandyFTP.
unt„tig
Server %d
Konnte Servertypen-Definitionen nicht ”ffnen.
Keine Servertypendefinitionen gefunden! Laufe im lokalen Modus!
Speichere Warteschlange als
Lade Warteschlange von
Sie mssen verbunden sein.
Anzulegendes Verzeichnis
Benenne \"%s\" um zu
L”sche \"%s\"
Warteschlange leer.
Quelle oder Ziel nicht verbunden.
Sie mssen einen Server w„hlen, fr den die Dateien in die Warteschlange gesetzt werden sollen.
Fehler beim Starten des Webbrowser.
Sind Sie sicher, daá Sie HandyFTP beenden wollen?
Laufwerk 
Sie mssen einen Server w„hlen, fr den die Dateien in die Warteschlange gesetzt werden sollen.
Neue Verbindung
Schlieáe Verbindung
Verbinde
Trenne
Beenden
Aus Warteschlange Entfernen
Zu Warteschlange Hinzufgen
Warteschlange Leeren
Server Sichern
Server L”schen
Aktualisieren
Voreinstellungen
Administration
Hilfe
šber
Konnte keine Datenverbindung herstellen.
LOCALE=2 Dansk
~Fil
~Tilpasning
~Hj‘lp
~Ny Strop
Flytte Strop
~Verbinde
~Trenne
Server ~sichern
Server ~l”schen
Be~enden
~Voreinstellungen
Server ~verwalten
~Automatisch verbinden
Autom. ~neu verbinden
~Standardsortierung
Navn
Dato
Stírrelse
Ingen
~Index
~Hj‘lp
~Systeminformation
Handy~FTP p† Web
š~ber
Sort.
Verzeichnis anlegen
Umbenennen
L”schen
Datei betrachten
Warteschlange speichern
Warteschlange laden
Datei entfernen
Absturz in %s, Zeile %d von %s. Bitte melden Sie dies an dbsoft@technologist.com
Seite %d von %
Einstellungen konnten nicht gespeichert werden. Inipath = \"%s\"
Gespeicherter Server \"%s\" ist nicht identisch!
Servertyp nicht gefunden! Benutze Standardeinstellungen.
Entferntes Verzeichnis empfangen.
Mit entferntem Verzeichnis verbunden.
Sende lokales LIST Kommando.
Fehler beim Empfangen des lokalen Verzeichnisses!
Von lokalem Verzeichnis getrennt.
Laufwerk %c:
Lokales Verzeichnis empfangen.
Mit lokalem Verzeichnis verbunden.
Stírrelse
Tid
Dato
Fehler beim Anlegen des Containers!
Ziel
Verzeichnis
Stírrelse
Tid
Dato
šber HandyFTP
Voreinstellungen
Allgemein
™ffne alle Server
Passiv-FTP
Zeige Passwort
URLs sichern
Spalten optimieren
Timeout
Wiederholversuche
Cache-Begrenzung
Bandbreiten-Begrenzung
Lokale
Ok
Annuller
IPS server ist nicht unt„tig.
IPS server ist nicht unt„tig.
IPS server ist nicht unt„tig.
Benutzer
Adresse
Aktivit„t
unt„tig
Socket
Konnte IPS Server nicht validieren.
IPS Administration
Schlieáen
Benutzer trennen
Herunterfahren
Neustarten
Administration
Servertyp
InetPowerServer
Andere
Erzeuge Verzeichnis \"%s\"
Benenne \"%s\" um in \"%s\"
Systeminformation
HandyFTP:\r\n\r\nErzeugt am: %s\r\nErzeugt um: %s\r\n\r\n
System:\r\n\r\nFarbtiefe: %lu\r\n
Bildschirmbreite: %d\r\nBildschirmh”he: %d\r\n\r\n
Dynamic Windows:\r\n\r\nVersion: %d.%d.%d\r\nErzeugt am: %s\r\nErzeugt um: %s\r\n\r\nBetriebssystem:\r\n\r\nSystem: %s\r\nVersion: %d.%d
\r\nStand: %d
Sendevorgang begonnen...
Empfang begonnen...
%d bytes %s in %d:%.2d (%.2fK/s ETA %d:%.2d).
versandt
empfangen
Von entferntem Verzeichnis getrennt.
šbertragung abgeschlossen. %d bytes empfangen in %d Sekunden (%.2fK/s).
Timeout berschritten beim Warten auf Unt„tigkeit des Servers.
Versuche Verbindung herzustellen... Bitte warten.
Kann Servername nicht aufl”sen.
Konnte keine Verbindung herstellen.
Verbunden mit %s auf Port %d.
Verbunden.
Sende QUIT-Nachricht an entfernten Server...
Verbindung mit %s auf Port %d geschlossen.
Warte auf Unt„tigkeit des Ziels. (%ds)
Zielserver nicht gefunden!
Konnte lokale Datei \"%s\" nicht finden.
Fehler beim Anbinden an Port der Datenverbindung.
M”glicherweise falsche Seitenkennung empfangen.
Konnte lokale Datei \"%s\" nicht finden.
Dieser Server ist ausgelastet.
Wechsle Arbeitsverzeichnis zu \"%s\".
Fataler FXP-Fehler! (THRDFXP) Abbruch.
Benutze Servertyp \"%s\" (%d)
Konnte Servertypen nicht laden, trenne.
Server gibt \"%s\" als Arbeitsverzeichnis an.
%s meldet Dateiname als nicht verfgbar.
%s meldet lokalen Fehler bei der Bearbeitung.
%s meldet unzureichenden Speicherplatz.
%s meldet Datei als nicht verfgbar.
%s meldet Seitentyp als unbekannt.
%s meldet šberschrietung der Speicherplatzbelegung.
%s meldet Dateiname als unzul„ssig.
Wechsle in den passiven Modus.
FXP-šbertragung erfolgreich abgeschlossen.
Wechsle Arbeitsverzeichnis zu \"%s\".
Fehler beim Anbinden an den Port der Datenverbindung.
Abbruch durch anderen Server, erneuter Versuch.
Fehler beim Herstellen der Verbindung.
Datenverbindung hergestellt.
Fataler FXP-Fehler! (STATUSFXPRETR) Abbruch.
Fataler FXP-Fehler! (STATUSFXPSTOR) Abbruch.
šbertragung abgeschlossen. %d bytes gesendet in %d Sekunden (%.2fK/s).
šbertragung abgeschlossen.
Maximale Anzahl der Versuche erreicht, fahre mit n„chstem Eintrag fort.
Letzter Reiter kann nicht entfernt werden.
Fehler beim Erzeugen der Datenpipes! Reitererzeugung abgebrochen.
Konnte neuen Reiter nicht erzeugen!
Seite 1 von 1
Servertitel:
Servername:
Port:
Benutzername:
Passwort:
Verzeichnis:
Ziel:
Welkommen til HandyFTP.
unt„tig
Server %d
Konnte Servertypen-Definitionen nicht ”ffnen.
Keine Servertypendefinitionen gefunden! Laufe im lokalen Modus!
Speichere Warteschlange als
Lade Warteschlange von
Sie mssen verbunden sein.
Anzulegendes Verzeichnis
Benenne \"%s\" um zu
L”sche \"%s\"
Warteschlange leer.
Quelle oder Ziel nicht verbunden.
Sie mssen einen Server w„hlen, fr den die Dateien in die Warteschlange gesetzt werden sollen.
Fehler beim Starten des Webbrowser.
Sind Sie sicher, daá Sie HandyFTP beenden wollen?
Laufwerk 
Sie mssen einen Server w„hlen, fr den die Dateien in die Warteschlange gesetzt werden sollen.
Neue Verbindung
Schlieáe Verbindung
Verbinde
Trenne
Beenden
Aus Warteschlange Entfernen
Zu Warteschlange Hinzufgen
Warteschlange Leeren
Server Sichern
Server L”schen
Aktualisieren
Voreinstellungen
Administration
Hj‘lp
šber
Konnte keine Datenverbindung herstellen.

