MESSAGES=186
LOCALE=1 Deutsch
~Datei
~Optionen
~Hilfe
~Neue Verbindung
S~chließe Verbindung
~Verbinde
~Trenne
Server ~sichern
Server ~löschen
Be~enden
~Voreinstellungen
Server ~verwalten
~Automatisch verbinden
Autom. ~neu verbinden
~Standardsortierung
nach Name
nach Datum
nach Größe
keine
~Index
~Hilfe
~Systeminformation
Handy~FTP im Web
Ü~ber
Sort.
Verzeichnis anlegen
Umbenennen
Löschen
Datei betrachten
Warteschlange speichern
Warteschlange laden
Datei entfernen
Absturz in %s, Zeile %d von %s. Bitte melden Sie dies an dbsoft@technologist.com
Seite %d von %
Einstellungen konnten nicht gespeichert werden. Inipath = \"%s\"
Gespeicherter Server \"%s\" ist nicht identisch!
Servertyp nicht gefunden! Benutze Standardeinstellungen.
Entferntes Verzeichnis empfangen.
Mit entferntem Verzeichnis verbunden.
Sende lokales LIST Kommando.
Fehler beim Empfangen des lokalen Verzeichnisses!
Von lokalem Verzeichnis getrennt.
Laufwerk %c:
Lokales Verzeichnis empfangen.
Mit lokalem Verzeichnis verbunden.
Größe
Zeit
Datum
Fehler beim Anlegen des Containers!
Ziel
Verzeichnis
Größe
Zeit
Datum
Über HandyFTP
Voreinstellungen
Allgemein
Öffne alle Server
Passiv-FTP
Zeige Passwort
URLs sichern
Spalten optimieren
Timeout
Wiederholversuche
Cache-Begrenzung
Bandbreiten-Begrenzung
Lokale
Ok
Abbrechen
IPS server ist nicht untätig.
IPS server ist nicht untätig.
IPS server ist nicht untätig.
Benutzer
Adresse
Aktivität
untätig
Socket
Konnte IPS Server nicht validieren.
IPS Administration
Schließen
Benutzer trennen
Herunterfahren
Neustarten
Administration
Servertyp
InetPowerServer
Andere
Erzeuge Verzeichnis \"%s\"
Benenne \"%s\" um in \"%s\"
Systeminformation
HandyFTP:\r\n\r\nVersion: %d.%d.%d\r\nErzeugt am: %s\r\nErzeugt um: %s\r\n\r\n
System:\r\n\r\nFarbtiefe: %lu\r\n
Bildschirmbreite: %d\r\nBildschirmhöhe: %d\r\n\r\n
Dynamic Windows:\r\n\r\nVersion: %d.%d.%d\r\nErzeugt am: %s\r\nErzeugt um: %s\r\n\r\nBetriebssystem:\r\n\r\nSystem: %s\r\nVersion: %d.%d
\r\nStand: %d
Sendevorgang begonnen...
Empfang begonnen...
%d bytes %s in %d:%.2d (%.2fK/s ETA %d:%.2d).
versandt
empfangen
Von entferntem Verzeichnis getrennt.
Übertragung abgeschlossen. %d bytes empfangen in %d Sekunden (%.2fK/s).
Timeout überschritten beim Warten auf Untätigkeit des Servers.
Versuche Verbindung herzustellen... Bitte warten.
Kann Servername nicht auflösen.
Konnte keine Verbindung herstellen.
Verbunden mit %s auf Port %d.
Verbunden.
Sende QUIT-Nachricht an entfernten Server...
Verbindung mit %s auf Port %d geschlossen.
Warte auf Untätigkeit des Ziels. (%ds)
Zielserver nicht gefunden!
Konnte lokale Datei \"%s\" nicht finden.
Fehler beim Anbinden an Port der Datenverbindung.
Möglicherweise falsche Seitenkennung empfangen.
Konnte lokale Datei \"%s\" nicht finden.
Dieser Server ist ausgelastet.
Wechsle Arbeitsverzeichnis zu \"%s\".
Fataler FXP-Fehler! (THRDFXP) Abbruch.
Benutze Servertyp \"%s\" (%d)
Konnte Servertypen nicht laden, trenne.
Server gibt \"%s\" als Arbeitsverzeichnis an.
%s meldet Dateiname als nicht verfügbar.
%s meldet lokalen Fehler bei der Bearbeitung.
%s meldet unzureichenden Speicherplatz.
%s meldet Datei als nicht verfügbar.
%s meldet Seitentyp als unbekannt.
%s meldet Überschrietung der Speicherplatzbelegung.
%s meldet Dateiname als unzulässig.
Wechsle in den passiven Modus.
FXP-Übertragung erfolgreich abgeschlossen.
Wechsle Arbeitsverzeichnis zu \"%s\".
Fehler beim Anbinden an den Port der Datenverbindung.
Abbruch durch anderen Server, erneuter Versuch.
Fehler beim Herstellen der Verbindung.
Datenverbindung hergestellt.
Fataler FXP-Fehler! (STATUSFXPRETR) Abbruch.
Fataler FXP-Fehler! (STATUSFXPSTOR) Abbruch.
Übertragung abgeschlossen. %d bytes gesendet in %d Sekunden (%.2fK/s).
Übertragung abgeschlossen.
Maximale Anzahl der Versuche erreicht, fahre mit nächstem Eintrag fort.
Letzter Reiter kann nicht entfernt werden.
Fehler beim Erzeugen der Datenpipes! Reitererzeugung abgebrochen.
Konnte neuen Reiter nicht erzeugen!
Seite 1 von 1
Servertitel:
Servername:
Port:
Benutzername:
Passwort:
Verzeichnis:
Ziel:
Willkommen bei HandyFTP.
untätig
Server %d
Konnte Servertypen-Definitionen nicht öffnen.
Keine Servertypendefinitionen gefunden! Laufe im lokalen Modus!
Speichere Warteschlange als
Lade Warteschlange von
Sie müssen verbunden sein.
Anzulegendes Verzeichnis
Benenne \"%s\" um zu
Lösche \"%s\"
Warteschlange leer.
Quelle oder Ziel nicht verbunden.
Sie müssen einen Server wählen, für den die Dateien in die Warteschlange gesetzt werden sollen.
Fehler beim Starten des Webbrowser.
Sind Sie sicher, daß Sie HandyFTP beenden wollen?
Laufwerk 
Sie müssen einen Server wählen, für den die Dateien in die Warteschlange gesetzt werden sollen.
Neue Verbindung
Schließe Verbindung
Verbinde
Trenne
Beenden
Aus Warteschlange Entfernen
Zu Warteschlange Hinzufügen
Warteschlange Leeren
Server Sichern
Server Löschen
Aktualisieren
Voreinstellungen
Administration
Hilfe
Über
Konnte keine Datenverbindung herstellen.
LOCALE=2 Dansk
~Fil
~Tilpasning
~Hjælp
~Ny Strop
Flytte Strop
~Verbinde
~Trenne
Server ~sichern
Server ~löschen
Be~enden
~Voreinstellungen
Server ~verwalten
~Automatisch verbinden
Autom. ~neu verbinden
~Standardsortierung
Navn
Dato
Størrelse
Ingen
~Index
~Hjælp
~Systeminformation
Handy~FTP på Web
Ü~ber
Sort.
Verzeichnis anlegen
Umbenennen
Löschen
Datei betrachten
Warteschlange speichern
Warteschlange laden
Datei entfernen
Absturz in %s, Zeile %d von %s. Bitte melden Sie dies an dbsoft@technologist.com
Seite %d von %
Einstellungen konnten nicht gespeichert werden. Inipath = \"%s\"
Gespeicherter Server \"%s\" ist nicht identisch!
Servertyp nicht gefunden! Benutze Standardeinstellungen.
Entferntes Verzeichnis empfangen.
Mit entferntem Verzeichnis verbunden.
Sende lokales LIST Kommando.
Fehler beim Empfangen des lokalen Verzeichnisses!
Von lokalem Verzeichnis getrennt.
Laufwerk %c:
Lokales Verzeichnis empfangen.
Mit lokalem Verzeichnis verbunden.
Størrelse
Tid
Dato
Fehler beim Anlegen des Containers!
Ziel
Verzeichnis
Størrelse
Tid
Dato
Über HandyFTP
Voreinstellungen
Allgemein
Öffne alle Server
Passiv-FTP
Zeige Passwort
URLs sichern
Spalten optimieren
Timeout
Wiederholversuche
Cache-Begrenzung
Bandbreiten-Begrenzung
Lokale
Ok
Annuller
IPS server ist nicht untätig.
IPS server ist nicht untätig.
IPS server ist nicht untätig.
Benutzer
Adresse
Aktivität
untätig
Socket
Konnte IPS Server nicht validieren.
IPS Administration
Schließen
Benutzer trennen
Herunterfahren
Neustarten
Administration
Servertyp
InetPowerServer
Andere
Erzeuge Verzeichnis \"%s\"
Benenne \"%s\" um in \"%s\"
Systeminformation
HandyFTP:\r\n\r\nVersion: %d.%d.%d\r\nErzeugt am: %s\r\nErzeugt um: %s\r\n\r\n
System:\r\n\r\nFarbtiefe: %lu\r\n
Bildschirmbreite: %d\r\nBildschirmhöhe: %d\r\n\r\n
Dynamic Windows:\r\n\r\nVersion: %d.%d.%d\r\nErzeugt am: %s\r\nErzeugt um: %s\r\n\r\nBetriebssystem:\r\n\r\nSystem: %s\r\nVersion: %d.%d
\r\nStand: %d
Sendevorgang begonnen...
Empfang begonnen...
%d bytes %s in %d:%.2d (%.2fK/s ETA %d:%.2d).
versandt
empfangen
Von entferntem Verzeichnis getrennt.
Übertragung abgeschlossen. %d bytes empfangen in %d Sekunden (%.2fK/s).
Timeout überschritten beim Warten auf Untätigkeit des Servers.
Versuche Verbindung herzustellen... Bitte warten.
Kann Servername nicht auflösen.
Konnte keine Verbindung herstellen.
Verbunden mit %s auf Port %d.
Verbunden.
Sende QUIT-Nachricht an entfernten Server...
Verbindung mit %s auf Port %d geschlossen.
Warte auf Untätigkeit des Ziels. (%ds)
Zielserver nicht gefunden!
Konnte lokale Datei \"%s\" nicht finden.
Fehler beim Anbinden an Port der Datenverbindung.
Möglicherweise falsche Seitenkennung empfangen.
Konnte lokale Datei \"%s\" nicht finden.
Dieser Server ist ausgelastet.
Wechsle Arbeitsverzeichnis zu \"%s\".
Fataler FXP-Fehler! (THRDFXP) Abbruch.
Benutze Servertyp \"%s\" (%d)
Konnte Servertypen nicht laden, trenne.
Server gibt \"%s\" als Arbeitsverzeichnis an.
%s meldet Dateiname als nicht verfügbar.
%s meldet lokalen Fehler bei der Bearbeitung.
%s meldet unzureichenden Speicherplatz.
%s meldet Datei als nicht verfügbar.
%s meldet Seitentyp als unbekannt.
%s meldet Überschrietung der Speicherplatzbelegung.
%s meldet Dateiname als unzulässig.
Wechsle in den passiven Modus.
FXP-Übertragung erfolgreich abgeschlossen.
Wechsle Arbeitsverzeichnis zu \"%s\".
Fehler beim Anbinden an den Port der Datenverbindung.
Abbruch durch anderen Server, erneuter Versuch.
Fehler beim Herstellen der Verbindung.
Datenverbindung hergestellt.
Fataler FXP-Fehler! (STATUSFXPRETR) Abbruch.
Fataler FXP-Fehler! (STATUSFXPSTOR) Abbruch.
Übertragung abgeschlossen. %d bytes gesendet in %d Sekunden (%.2fK/s).
Übertragung abgeschlossen.
Maximale Anzahl der Versuche erreicht, fahre mit nächstem Eintrag fort.
Letzter Reiter kann nicht entfernt werden.
Fehler beim Erzeugen der Datenpipes! Reitererzeugung abgebrochen.
Konnte neuen Reiter nicht erzeugen!
Seite 1 von 1
Servertitel:
Servername:
Port:
Benutzername:
Passwort:
Verzeichnis:
Ziel:
Welkommen til HandyFTP.
untätig
Server %d
Konnte Servertypen-Definitionen nicht öffnen.
Keine Servertypendefinitionen gefunden! Laufe im lokalen Modus!
Speichere Warteschlange als
Lade Warteschlange von
Sie müssen verbunden sein.
Anzulegendes Verzeichnis
Benenne \"%s\" um zu
Lösche \"%s\"
Warteschlange leer.
Quelle oder Ziel nicht verbunden.
Sie müssen einen Server wählen, für den die Dateien in die Warteschlange gesetzt werden sollen.
Fehler beim Starten des Webbrowser.
Sind Sie sicher, daß Sie HandyFTP beenden wollen?
Laufwerk 
Sie müssen einen Server wählen, für den die Dateien in die Warteschlange gesetzt werden sollen.
Neue Verbindung
Schließe Verbindung
Verbinde
Trenne
Beenden
Aus Warteschlange Entfernen
Zu Warteschlange Hinzufügen
Warteschlange Leeren
Server Sichern
Server Löschen
Aktualisieren
Voreinstellungen
Administration
Hjælp
Über
Konnte keine Datenverbindung herstellen.

